openapi: 3.0.0
info:
  version: '1.2'
  title: CBETA API
  description: API to access CBETA Chinese Buddhist Texts Resources.

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Ray.Chou/CBETA-API/1.2
  - url: http://cbdata.dila.edu.tw/v1.2
    description: Main server
  - url: http://api.cbetaonline.cn/
    description: Mirror server

paths:
  /catalog_entry:
    get:
      summary: Returns a catalog entry information, including its children.
      parameters:
        - $ref: 'https://raw.githubusercontent.com/DILA-edu/cbeta-api/main/openapi/catalog-entry-parameters.yaml#/q'
        - $ref: 'https://raw.githubusercontent.com/DILA-edu/cbeta-api/main/openapi/catalog-entry-parameters.yaml#/vol'
      responses:
        '200':
          description: A Catalog Entry Object
          content:
            application/json:
              schema: 
                $ref: 'http://cbdata.dila.edu.tw/v1.2/openapi/catalog-entry-response.yaml'