openapi: 3.0.0
info:
  version: '1.2'
  title: CBETA API
  description: API to access CBETA Chinese Buddhist Texts Resources.

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Ray.Chou/CBETA-API/1.2
  - url: http://cbdata.dila.edu.tw/v1.2
    description: Main server
  - url: http://api.cbetaonline.cn/
    description: Mirror server

paths:
  /catalog_entry:
    get:
      summary: Returns a catalog entry information, including its children.
      parameters:
        - name: q
          in: query
          required: false
          description: Catalog Entry ID
          example: CBETA.001
          schema:
            type: string
        - name: vol
          in: query
          required: false
          description: volume. This parameter is incompatible with `q`.
          example: T01
          schema:
            type: string
      responses:
        '200':
          description: A Catalog Entry Object
          content:
            application/json:
              schema: 
                type: object
                properties:
                  num_found:
                    type: integer
                    description: number of child entries
                  label:
                    type: string
                    description: catalog entry label
                  results:
                    type: array
                    description: list of child entries
                    items:
                      type: object
                      properties:
                        n:
                          type: string
                          description: child entry id
                        label:
                          type: string
                          description: child entry label
                        node_type:
                          type: string
                          description: 如果 node_type 為 'alt' 表示 CBETA 未收錄此經全文，而是對應到其他藏經的全文。
                        juan_start:
                          type: integer
                          description: 目錄節點所指向的可能是某部典籍的部份卷數，例如：`http://cbdata.dila.edu.tw/v1.2/catalog_entry?q=CBETA.003.001`
                        juan_end:
                          type: integer
                        file:
                          type: string